image: docker.autonubil.net/shared/magarac:latest

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - gocache
        - .sonar/cache
        - app/

stages:
    - validate
    - build

sonar:
    stage: validate
    script:
        - mkdir -p /root/.sonar/cache
        - sonar-scanner -Dsonar.projectKey=$CI_PROJECT_NAME -Dsonar.sources=. -Dsonar.login=$SONAR_TOKEN -Duser.home=/root/ -Dsonar.exclusions="client/**, models/**" || true
        - ls -al /root/.sonar/

build:
    stage: build
    script: |
        export ROOT=$(pwd)
        mkdir -p app/
        mkdir -p /root/gocache
        go get .
        GOCACHE=${ROOT}/gocache CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w -linkmode=external -v -X main.Version=${CI_COMMIT_REF_NAME} -X main.BuildDate=$(date --iso-8601=seconds) -X main.Commit=$CI_COMMIT_SHA -s" -v -o ${ROOT}/${CI_PROJECT_NAME} main.go
        upx ${ROOT}/${CI_PROJECT_NAME}
        nexus_publish_artifact.sh ${ROOT}/${CI_PROJECT_NAME} terraform/${CI_PROJECT_NAME}/linux/amd64
    artifacts:
      paths:
      - ${CI_PROJECT_NAME}
    only:
      - master


build_linux_release:
    stage: build
    script: |
        export ROOT=$(pwd)
        mkdir -p app/
        mkdir -p /root/gocache
        go get .
        GOCACHE=${ROOT}/gocache CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w -linkmode=external -v -X main.Version=${CI_COMMIT_REF_NAME} -X main.BuildDate=$(date --iso-8601=seconds) -X main.Commit=$CI_COMMIT_SHA -s" -v -o ${ROOT}/${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME} main.go
        upx ${ROOT}/${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}
        nexus_publish_artifact.sh ${ROOT}/${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME} terraform/${CI_PROJECT_NAME}/linux/amd64
    artifacts:
      paths:
      - ${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}
    only:
        - tags


build_windows_release:
    stage: build
    script: |
        export ROOT=$(pwd)
        mkdir -p app/
        mkdir -p /root/gocache
        go get .
        GOCACHE=${ROOT}/gocache CGO_ENABLED=1 GOOS=windows GOARCH=amd64 CC=x86_64-w64-mingw32-gcc  go build -ldflags "-s -w -linkmode=external -v -X main.Version=${CI_COMMIT_REF_NAME} -X main.BuildDate=$(date --iso-8601=seconds) -X main.Commit=$CI_COMMIT_SHA -s"  -v -o ${ROOT}/${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}.exe main.go
        nexus_publish_artifact.sh ${ROOT}/${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}.exe terraform/${CI_PROJECT_NAME}/windows/amd64
    artifacts:
      paths:
      - ${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}
    only:
        - tags
    
build_darwin_release:
    stage: build
    script: |
        export ROOT=$(pwd)
        mkdir -p app/
        mkdir -p /root/gocache
        go get .
        GOCACHE=${ROOT}/gocache GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w  -v -X main.Version=${CI_COMMIT_REF_NAME} -X main.BuildDate=$(date --iso-8601=seconds) -X main.Commit=$CI_COMMIT_SHA -s"  -v -o ${ROOT}/${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME} main.go
        nexus_publish_artifact.sh ${ROOT}/${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME} terraform/${CI_PROJECT_NAME}/darwin/amd64
    artifacts:
      paths:
      - ${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}
    only:
        - tags
    