// Code generated by gobind. DO NOT EDIT.

// Java class gowazuh.AgentConfig is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/autonubil/go-wazuh/gowazuh
package gowazuh;

import go.Seq;

/**
 * AgentConfig is a plain struct that gobind will turn into a Java class
 */
public final class AgentConfig implements Seq.Proxy {
	static { Gowazuh.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	AgentConfig(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public AgentConfig() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public final native String getServer();
	public final native void setServer(String v);
	
	public final native String getAgentID();
	public final native void setAgentID(String v);
	
	public final native String getAgentName();
	public final native void setAgentName(String v);
	
	public final native String getAgentKey();
	public final native void setAgentKey(String v);
	
	public final native String getClientName();
	public final native void setClientName(String v);
	
	public final native String getClientVersion();
	public final native void setClientVersion(String v);
	
	public final native boolean getUseUDP();
	public final native void setUseUDP(boolean v);
	
	public final native long getPort();
	public final native void setPort(long v);
	
	public final native String getAgentIP();
	public final native void setAgentIP(String v);
	
	public final native String getBasePath();
	public final native void setBasePath(String v);
	
	public final native String getAllowedIPs();
	public final native void setAllowedIPs(String v);
	
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof AgentConfig)) {
		    return false;
		}
		AgentConfig that = (AgentConfig)o;
		String thisServer = getServer();
		String thatServer = that.getServer();
		if (thisServer == null) {
			if (thatServer != null) {
			    return false;
			}
		} else if (!thisServer.equals(thatServer)) {
		    return false;
		}
		String thisAgentID = getAgentID();
		String thatAgentID = that.getAgentID();
		if (thisAgentID == null) {
			if (thatAgentID != null) {
			    return false;
			}
		} else if (!thisAgentID.equals(thatAgentID)) {
		    return false;
		}
		String thisAgentName = getAgentName();
		String thatAgentName = that.getAgentName();
		if (thisAgentName == null) {
			if (thatAgentName != null) {
			    return false;
			}
		} else if (!thisAgentName.equals(thatAgentName)) {
		    return false;
		}
		String thisAgentKey = getAgentKey();
		String thatAgentKey = that.getAgentKey();
		if (thisAgentKey == null) {
			if (thatAgentKey != null) {
			    return false;
			}
		} else if (!thisAgentKey.equals(thatAgentKey)) {
		    return false;
		}
		String thisClientName = getClientName();
		String thatClientName = that.getClientName();
		if (thisClientName == null) {
			if (thatClientName != null) {
			    return false;
			}
		} else if (!thisClientName.equals(thatClientName)) {
		    return false;
		}
		String thisClientVersion = getClientVersion();
		String thatClientVersion = that.getClientVersion();
		if (thisClientVersion == null) {
			if (thatClientVersion != null) {
			    return false;
			}
		} else if (!thisClientVersion.equals(thatClientVersion)) {
		    return false;
		}
		boolean thisUseUDP = getUseUDP();
		boolean thatUseUDP = that.getUseUDP();
		if (thisUseUDP != thatUseUDP) {
		    return false;
		}
		long thisPort = getPort();
		long thatPort = that.getPort();
		if (thisPort != thatPort) {
		    return false;
		}
		String thisAgentIP = getAgentIP();
		String thatAgentIP = that.getAgentIP();
		if (thisAgentIP == null) {
			if (thatAgentIP != null) {
			    return false;
			}
		} else if (!thisAgentIP.equals(thatAgentIP)) {
		    return false;
		}
		String thisBasePath = getBasePath();
		String thatBasePath = that.getBasePath();
		if (thisBasePath == null) {
			if (thatBasePath != null) {
			    return false;
			}
		} else if (!thisBasePath.equals(thatBasePath)) {
		    return false;
		}
		String thisAllowedIPs = getAllowedIPs();
		String thatAllowedIPs = that.getAllowedIPs();
		if (thisAllowedIPs == null) {
			if (thatAllowedIPs != null) {
			    return false;
			}
		} else if (!thisAllowedIPs.equals(thatAllowedIPs)) {
		    return false;
		}
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {getServer(), getAgentID(), getAgentName(), getAgentKey(), getClientName(), getClientVersion(), getUseUDP(), getPort(), getAgentIP(), getBasePath(), getAllowedIPs()});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("AgentConfig").append("{");
		b.append("Server:").append(getServer()).append(",");
		b.append("AgentID:").append(getAgentID()).append(",");
		b.append("AgentName:").append(getAgentName()).append(",");
		b.append("AgentKey:").append(getAgentKey()).append(",");
		b.append("ClientName:").append(getClientName()).append(",");
		b.append("ClientVersion:").append(getClientVersion()).append(",");
		b.append("UseUDP:").append(getUseUDP()).append(",");
		b.append("Port:").append(getPort()).append(",");
		b.append("AgentIP:").append(getAgentIP()).append(",");
		b.append("BasePath:").append(getBasePath()).append(",");
		b.append("AllowedIPs:").append(getAllowedIPs()).append(",");
		return b.append("}").toString();
	}
}

