// Code generated by gobind. DO NOT EDIT.

// Java class gowazuh.Gowazuh is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/autonubil/go-wazuh/gowazuh
package gowazuh;

import go.Seq;

public abstract class Gowazuh {
	static {
		Seq.touch(); // for loading the native library
		_init();
	}
	
	private Gowazuh() {} // uninstantiable
	
	// touch is called from other bound packages to initialize this package
	public static void touch() {}
	
	private static native void _init();
	
	
	
	// skipped function GetMobile with unsupported parameter or return types
	
	public static native WazuhClient newWazuhClient(AgentConfig cfg) throws Exception;
}
