// Code generated by gobind. DO NOT EDIT.

// Java class gowazuh.WazuhClient is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/autonubil/go-wazuh/gowazuh
package gowazuh;

import go.Seq;

public final class WazuhClient implements Seq.Proxy {
	static { Gowazuh.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	public WazuhClient(AgentConfig cfg) {
		this.refnum = __NewWazuhClient(cfg);
		Seq.trackGoRef(refnum, this);
	}
	
	private static native int __NewWazuhClient(AgentConfig cfg);
	
	WazuhClient(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof WazuhClient)) {
		    return false;
		}
		WazuhClient that = (WazuhClient)o;
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("WazuhClient").append("{");
		return b.append("}").toString();
	}
}

